apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-local-cicd
  namespace: argocd
spec:
  destination:
    namespace: devops-local-cicd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/AndreyKotsenko/devops-local-cicd
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
