apiVersion: v1
kind: Service
metadata:
  name: devops-local-cicd-container-service
spec:
  selector:
    app: devops-local-cicd-container
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
